/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ICodex:checklist': typeof import('~icons/codex/checklist')['default']
    'ICodex:directionDownRight': typeof import('~icons/codex/direction-down-right')['default']
  }
}

// For TSX support - ts适配的正确语法
declare module '@vue/runtime-dom' {
  interface IntrinsicElementAttributes {
    'i-codex:checklist': any
    'i-codex:direction-down-right': any
  }
}
